import { z } from "zod";

export const StatisticsSchema = z.object({
  MsTimeStamp: z.number(),
  Accumulated: z.object({
    PktSent: z.number(),
    PktRecv: z.number(),
    PktSentUnique: z.number(),
    PktRecvUnique: z.number(),
    PktSendLoss: z.number(),
    PktRecvLoss: z.number(),
    PktRetrans: z.number(),
    PktRecvRetrans: z.number(),
    PktSentACK: z.number(),
    PktRecvACK: z.number(),
    PktSentNAK: z.number(),
    PktRecvNAK: z.number(),
    PktSentKM: z.number(),
    PktRecvKM: z.number(),
    UsSndDuration: z.number(),
    PktRecvBelated: z.number(),
    PktSendDrop: z.number(),
    PktRecvDrop: z.number(),
    PktRecvUndecrypt: z.number(),

    ByteSent: z.number(),
    ByteRecv: z.number(),
    ByteSentUnique: z.number(),
    ByteRecvUnique: z.number(),
    ByteRecvLoss: z.number(),
    ByteRetrans: z.number(),
    ByteRecvRetrans: z.number(),
    ByteRecvBelated: z.number(),
    ByteSendDrop: z.number(),
    ByteRecvDrop: z.number(),
    ByteRecvUndecrypt: z.number(),
  }),

  Interval: z.object({
    MsInterval: z.number(),

    PktSent: z.number(),
    PktRecv: z.number(),
    PktSentUnique: z.number(),
    PktRecvUnique: z.number(),
    PktSendLoss: z.number(),
    PktRecvLoss: z.number(),
    PktRetrans: z.number(),
    PktRecvRetrans: z.number(),
    PktSentACK: z.number(),
    PktRecvACK: z.number(),
    PktSentNAK: z.number(),
    PktRecvNAK: z.number(),

    MbpsSendRate: z.number(),
    MbpsRecvRate: z.number(),

    UsSndDuration: z.number(),

    PktReorderDistance: z.number(),
    PktRecvBelated: z.number(),
    PktSndDrop: z.number(),
    PktRecvDrop: z.number(),
    PktRecvUndecrypt: z.number(),

    ByteSent: z.number(),
    ByteRecv: z.number(),
    ByteSentUnique: z.number(),
    ByteRecvUnique: z.number(),
    ByteRecvLoss: z.number(),
    ByteRetrans: z.number(),
    ByteRecvRetrans: z.number(),
    ByteRecvBelated: z.number(),
    ByteSendDrop: z.number(),
    ByteRecvDrop: z.number(),
    ByteRecvUndecrypt: z.number(),
  }),

  Instantaneous: z.object({
    UsPktSendPeriod: z.number(),
    PktFlowWindow: z.number(),
    PktFlightSize: z.number(),
    MsRTT: z.number(),
    MbpsSentRate: z.number(),
    MbpsRecvRate: z.number(),
    MbpsLinkCapacity: z.number(),
    ByteAvailSendBuf: z.number(),
    ByteAvailRecvBuf: z.number(),
    MbpsMaxBW: z.number(),
    ByteMSS: z.number(),
    PktSendBuf: z.number(),
    ByteSendBuf: z.number(),
    MsSendBuf: z.number(),
    MsSendTsbPdDelay: z.number(),
    PktRecvBuf: z.number(),
    ByteRecvBuf: z.number(),
    MsRecvBuf: z.number(),
    MsRecvTsbPdDelay: z.number(),
    PktReorderTolerance: z.number(),
    PktRecvAvgBelatedTime: z.number(),
    PktSendLossRate: z.number(),
    PktRecvLossRate: z.number(),
  }),
});

export const WebSocketMessageSchema = z.object({
  timestamp: z.string(),
  type: z.enum(["reader", "writer"]),
  stats: StatisticsSchema,
});
